### ISSUE TITLE
Dev-Server not working with per environment configuration & instant analytics

### ISSUE THREAD

**Issue by sarahschuetz** [nystudio107/craft-plugin-vite#14]
### Describe the bug
Vite build works, but changes with dev-server are not loaded.

My configuration:
```
return [
    '*' => [
        'useDevServer' => false,
        'manifestPath' => '@webroot/dist/manifest.json',
        'serverPublic' => App::env('SITE_URL') . '/dist/',
        'errorEntry' => 'app.js',
        'cacheKeySuffix' => '',
        'devServerInternal' => '',
        'checkDevServer' => false,
        'includeReactRefreshShim' => false,
        'includeModulePreloadShim' => true,
        'criticalPath' => '@webroot/dist/criticalcss',
        'criticalSuffix' =>'_critical.min.css',
    ],

    'production'  => [
    ],

    'staging'  => [
    ],

    'dev'  => [
        'useDevServer' => true,
        'devServerPublic' => 'http://localhost:3000/',
    ],
];
```

When I put
```
  'useDevServer' => true,
  'devServerPublic' => 'http://localhost:3000/',
```
in the * section, it works.

When I dump the environment in the plugin source code. It shows that Craft CMS is running in `dev` environment, correctly.

The strange thing is, if I dump ` dd($this->devServerInternal);` in the Vite Plugin the result is
`http://craft-instantanalytics-buildchain:3001` (from the also installed instant analytics plugin).

### Versions
- Vite Plugin version: 4.0.5
- Instant Analytics version: 4.0.2
- Craft version: 4.3.7.1

**Comment by khalwat** [comment]
Because we don't want the dev server to come into the mix unless you are intentionally developing a plugin, it checks for the `VITE_PLUGIN_DEVSERVER` constant being set in the `.env`:

https://github.com/nystudio107/craft-plugin-vite/blob/develop/src/services/VitePluginService.php#L37

So you'll need to have that in your `.env`. More here:

https://nystudio107.com/blog/a-craft-cms-plugin-local-development-environment

**Comment by sarahschuetz** [comment]
@khalwat we are not developing a plugin. The problem was that the dev server was not working for our templates.
Fixed it by renaming `ENVIRONMENT` to `CRAFT_ENVIRONMENT` in my env file. Craft was using Dev mode with the old naming however the plugin thought we were in production mode.
