### ISSUE TITLE
Would love to natively remove site styles on error entries!

### ISSUE THREAD

**Issue by J-Protz** [nystudio107/craft-plugin-vite#16]
### Is your feature request related to a problem? Please describe.
Not necessarily! When you set error entry to your main.js, and your js file includes site styles, these override the Craftcms error log styles. For a while I (dumbly) thought it was a craft dark mode update or something lol, but it made the error logs very hard to read.

### Describe the solution you would like
I would love if the plugin could detect a 500 error and not include the style tag, or remove it natively.

### Describe alternatives you have considered
I have a homemade solution in my js, but it's not ideal, as things could change with craft and plugin updates, and I am making assumptions. Here is the code though.

```js
    // when we run into twig errors, the site styles make it impossible to read.
    // the error entry has no class on the body, and our layout always does, so this
    // is a way to check if we are in an error entry.
    // we use the title as a fallback, as well as the domain because we REALLY
    // do not want this to happen on production
    ;(function removeStylesOnDevErrorEntry() {
        if (
            !document.querySelector('body').hasAttribute('class') &&
            document.title.toLowerCase().includes('error') &&
            domain.includes('test')
        ) {
            const myStyles = document.querySelector('style[data-vite-dev-id]')
              if(myStyles) {myStyles.remove()}
        }
    })()

```

## Without my removal : 
<img width="1464" alt="Screen Shot 2023-06-11 at 11 07 28 AM" src="https://github.com/nystudio107/craft-plugin-vite/assets/70289763/f0b0d55c-a4fb-4c18-aa87-ee09dc5405da">

**Comment by khalwat** [comment]
This is probably beyond the scope of the plugin.

If this is truly an issue, you can not include your CSS via the JavaScript entry, and instead via another JS entrypoint or separate it out into it's own entry.
