### ISSUE TITLE
Vite Plugin and frontend templates w template hooks

### ISSUE THREAD

**Issue by isaacwingate** [nystudio107/craft-plugin-vite#18]
I'm currently using Template Hooks to serve frontend templates from my plugin. I was wondering if it is still possible to use Vite with this setup? 

To test, I downloaded your transcoder plugin and added in a template hook. However, I can only get the HMR to work if I keep the /transcoder/welcome page open in a seperate tab.

**Comment by khalwat** [comment]
I need more information to be able to answer this question. Can you please give me an example with code showing what you're doing?

**Comment by isaacwingate** [comment]
blah

**Comment by isaacwingate** [comment]
I have added the following template hook inside of `installSiteEventListeners()`

        // Transcoder.php
        \yii\base\Event::on(
            \craft\web\View::class,
            \craft\web\View::EVENT_REGISTER_SITE_TEMPLATE_ROOTS,
            function(\craft\events\RegisterTemplateRootsEvent $event) {
                $event->roots['frontend-new'] = __DIR__ . '/templates/frontend';
            }
        );

        Craft::$app->getView()->hook('intro-block-new', function(array &$context) {
            $templatePath = 'frontend-new/introBlock/template';
            
            $html = Craft::$app->view->renderTemplate(
                $templatePath, $context, Craft::$app->view::TEMPLATE_MODE_SITE
            );
            return $html;
        });

/templates/frontend/introBlock/template.twig

    {% do view.registerAssetBundle("nystudio107\\transcoder\\assetbundles\\transcoder\\TranscoderAsset") %}

    {% set tagOptions = {
        'depends': [
            'nystudio107\\transcoder\\assetbundles\\transcoder\\TranscoderAsset'
        ],
    } %}
    {{ craft.transcoder.register('src/js/welcome.ts', false, tagOptions, tagOptions) }}

    {% block content %}

            <div id="app-container">
            </div>

            <h1>test</h1>
            
    {% endblock %}
    
In the homepage of my site I'm calling the hook like so: `{% hook 'intro-block-new' %}`

When running `make dev` I can only get vite to rebuild If visit `/admin/transcoder/welcome`. Once I visit that URL, I can then go to my homepage and see the changes every time I save code.

**Comment by khalwat** [comment]
Sorry I missed responding to this.

I'm confused about the use of Transcoder code (a plugin of mine) in this example here?

I'm also still unfortunately confused about exactly what's going wrong.

You're saying that Vite won't detect changes you make to the JS/CSS it is running via the dev server unless you a visit a frontend web page?

This doesn't sound right... Vite should be monitoring for changes to files it is watching via the dev server whether a page is loaded or not. Sounds like some kind of a setup/devops issue that likely doesn't have anything to do with `craft-plugin-vite`
