### ISSUE TITLE
Cache busting with [hash] as queryparameter instead of filename

### ISSUE THREAD

**Issue by Tim-Wils** [nystudio107/craft-plugin-vite#20]
Hi Andrew!
We use the craft.vite.script() function to create tags automagically, but we now walk into something of a feature request.
We're building the assets _without hash_, but we want to make use of the hash that's in manifest as a cache-busting mechanism.

I know I could place all the script/links tags manually in the layout and paste `?v={{ craft.vite.getCssHash("src/js/app.ts") }}` behind every url.
But it would be awesome to have if we can do this as an extra parameter in the .script() function like below and keep the awesomeness that .script() is generating:

```
{{ craft.vite.script("src/js/app.ts", true,{},{},{
queryparams: 'v='~craft.vite.getCssHash("src/js/app.ts")
}) }}
```

What do you think of this?

Cheers!

**Comment by khalwat** [comment]
Yeah I'd recommend building the assets with a hash -- is there a specific reason you're not doing that?
