### ISSUE TITLE
craft.vite.getCssHash no longer working as expected

### ISSUE THREAD

**Issue by martyspain** [nystudio107/craft-plugin-vite#21]
### Describe the bug
The default format for files outputted by Vite/Rollup is now [name]-[hash].[extension] rather than [name].[hash].[extension].

This means that the `{{ craft.vite.getCssHash() }}` function no longer works as intended, because it's looking for the first `.` in the filename and not finding one, which means the hash that's returned is malformed because the offset passed to `substr` on line 110  of `Services/Helper.php` is always 1.

For example, a CSS file output from Vite might look like this:

`main-PF0JF2pS.css`

Calling `{{ craft.vite.getCssHash('main-PF0JF2pS.css') }}` will currently return the following:

`ain-PF0JF2pS`

### Expected behaviour

In the example above, the expected output from `{{ craft.vite.getCssHash('main-PF0JF2pS.css') }}` would be:

`PF0JF2pS`

### Versions
- Plugin version: 4.0.6
- Craft version: 4.5.11.1
- Vite version: 5.0.6

**Comment by khalwat** [comment]
Addressed via: https://github.com/nystudio107/craft-vite/commit/fe690df503962bb144e6aab4f7111563e9ed17a4 & https://github.com/nystudio107/craft-vite/commit/cbeafe9f1d5b7069c8ebc6fd75c734241b435358

Craft CMS 3:

You can try it now by setting your server in your `composer.json` to look like this:
```json
    "nystudio107/craft-vite": "dev-develop as 1.0.32”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your server in your `composer.json` to look like this:
```json
    "nystudio107/craft-vite": "dev-develop-v4 as 4.0.7”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
lmk if this fixes it for you, and I will cut a release.

**Comment by martyspain** [comment]
@khalwat Yes, that works a treat (tested on Craft 4). Thanks for resolving this so quickly!
