### ISSUE TITLE
Auto reload not happening on twig template changes

### ISSUE THREAD

**Issue by mhill601** [nystudio107/craft-plugin-vite#4]
I've setup a local environment and everything is working as expected except that auto reloading isn't happening whenever twig files are modified. CSS and Javascript files are all loaded with HMR as expected so this is only browser reload. The vite.config.js was pulled straight from your repo (link below).

https://github.com/nystudio107/craft/blob/craft-vite/buildchain/vite.config.js

I've attempted to modify the settings passed into VitePlugin, but haven't been able to get it to work.

Any ideas on what I could start looking at to find the issue?

### Versions
- Plugin version:1.0.17
- Craft version:3.6.4

**Comment by khalwat** [comment]
This is not going to be an issue with the plugin itself, but rather a config issue for Vite.

What is your local dev environment?

**Comment by khalwat** [comment]
Likely fixed in Vite 2.7
