### ISSUE TITLE
Production build will output no assets

### ISSUE THREAD

**Issue by watarutmnh** [nystudio107/craft-plugin-vite#6]
### Describe the bug
My production build outputs no assets. It seems to be working fine if I revert the commit below.
[Resolving issue where assets never served for production builds](https://github.com/nystudio107/craft-plugin-vite/commit/ff9fc2e3e4884aa56e9554db145da759373f7590)

### Versions
- Plugin version: 1.0.19
- Craft version: 3.7.26

**Comment by baileydoestech** [comment]
Seeing the same issue

**Comment by khalwat** [comment]
Sigh. On it.

**Comment by khalwat** [comment]
Fixed in 1.0.20 -> https://github.com/nystudio107/craft-vite/releases/tag/1.0.20
